/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Askisi1;

import java.util.HashSet;

/**
 *
 * @author Panagiotis
 */
public class Askisi1_3 extends javax.swing.JFrame {

    /**
     * Creates new form Askisi1_3
     */
    public Askisi1_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Encode = new javax.swing.JButton();
        btn_Decode = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        txtfld_PlainText = new javax.swing.JTextField();
        txtfld_CipherText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Αποκωδικοποιητής");

        btn_Encode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Encode.setText("Κωδικοποίηση");
        btn_Encode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EncodeActionPerformed(evt);
            }
        });

        btn_Decode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Decode.setText("Αποκωδικοποίηση");
        btn_Decode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DecodeActionPerformed(evt);
            }
        });

        btn_Reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Reset.setText("Επαναφορά");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        txtfld_PlainText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtfld_CipherText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Αρχικό κείμενο");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Κωδικοποιημένο κείμενο");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Encode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(btn_Decode)
                                .addGap(40, 40, 40)
                                .addComponent(btn_Reset))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfld_PlainText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfld_CipherText, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(txtfld_PlainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfld_CipherText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Encode)
                    .addComponent(btn_Decode)
                    .addComponent(btn_Reset))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EncodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EncodeActionPerformed
        // TODO add your handling code here:
        StringBuilder tmpText = new StringBuilder(txtfld_PlainText.getText());
        for (int i = 0; i < tmpText.length(); i++)
            tmpText.setCharAt(i, (char)(tmpText.charAt(i) + 1));
        txtfld_CipherText.setText(tmpText.toString());        
    }//GEN-LAST:event_btn_EncodeActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        // TODO add your handling code here:
        txtfld_PlainText.setText("");
        txtfld_CipherText.setText("");

    }//GEN-LAST:event_btn_ResetActionPerformed

    private void btn_DecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DecodeActionPerformed
        // TODO add your handling code here:
        StringBuilder tmpText = new StringBuilder(txtfld_CipherText.getText());
        for (int i = 0; i < tmpText.length(); i++)
            tmpText.setCharAt(i, (char)(tmpText.charAt(i) - 1));
        txtfld_PlainText.setText(tmpText.toString());
    }//GEN-LAST:event_btn_DecodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Askisi1_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Askisi1_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Askisi1_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Askisi1_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Askisi1_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Decode;
    private javax.swing.JButton btn_Encode;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtfld_CipherText;
    private javax.swing.JTextField txtfld_PlainText;
    // End of variables declaration//GEN-END:variables
}
